appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: DmiiXxgvN7NuuVOLvjS6E6bVLCewqbCOl/Fz651ZXfBjPvxEiwqz4xiIGPCTM2o53nUoTXJCOSGOKbHT/lpSlJSU67FwdkIdy4b1UUG0UUChbAvaHR9rCWvX3DQTmct2V9LWb4coFp1UlIijBnyj3K/sEg4wXCz95ZtnHvOO6LkNO4emJdWn2lkQA8rfvxh+GbPeThlU0OT925omtK2uEJHZNCRh4qKGGD++uopfY/dMfDnUy0vHxheC1NaywdUVNH0U2opVr8xT1V++wo6Y5GFLrTdMOqdtd57sWtii89bqVVFR2tzc93/7mi88EaDNM7ycIPwKhCYJVLHDlViVOcBfwAeh0kENdBydtN3ZLcm7kfAh3LPOnsg8AzYQy71QRBO86VOBEDXGmVGwO6gNaHw+dcPaB8KjRfbqC57+WTZTpPGwrWwl4pyijhWSAHo8ZQWjaFl5lyUImYo8ZazvF+whzPEbOM7iD//Lw1L4XFgKc2/xOgLiHW1T8Qdb2nGWw/XHrysrvLfjbBWVGvsgGKFYzkcnBwh0db1eMZ7ZG1dr4kqGSXhqSXRLM4wASYJq2y5C2t/u6KksB6uQOY/kQQTcBPX4OHXhhW5e15EmfzJYBpdgtsP8oN0+1WHA8/O0FYWQVfHm5/6c7QdMI3G4DTjEDNAbMeZkZstE3QY9cu4=
conda_forge_output_validation: true
